### ISSUE TITLE
공개 API

### ISSUE THREAD

**Issue by yossogood8611** [NowEscape/now_escape#1]
공개 API 있는 업체 찾기
- 직접 문의드리기
- 검색
- ...

**Comment by yossogood8611** [comment]
크롤링 규제 확인 관련 : https://yozm.wishket.com/magazine/detail/878/

- 방탈출 단편선 : https://www.dpsnnn.com/robots.txt  : join, login, shop_cart 제외 모두 허용
- 넥스트 에디션 : https://www.nextedition.co.kr/robots.txt  : 모두 허용
- 머더파커 : http://www.murderparker.com/robots.txt  : Yeti (네이버) 만 모두 허용
- 솔버 : http://solver-gd.com/robots.txt : admin, api 제외 허용
- 덤앤더머 : http://www.dumbndumber.kr/robots.txt : 모두 허용
- 이스케이퍼스 : http://escapers.or.kr/robots.txt : Disallow: 빈칸 표시
- 히든스위치 : http://hidden-switch.com/robots.txt : Yeti 모두 허용
- 디코더 : http://decoder.kr/robots.txt : 모두 허용
- 지구별 방탈출 : https://xn--2e0b040a4xj.com/robots.txt : Disallow: 빈칸 표시 


- 키이스케이프, 포인트나인, 도어이스케이프, 비트포비아, 비밀의 화원,싸인이스케이프,...   : 
Not Found 혹은 페이지 그대로. Not Found의 경우 구글에서는 크롤링을 모두 허용한다는 의미로 받아들임. 홈페이지가 그대로인 경우 (키이스케이프, 포인트나인, ...)의 경우는 다른 방식으로 개발해서 robots.txt를 따로 찾아야 할 수 있음

크롤링 프로그램을 만들면 자동으로 robots.txt 를 읽어와 확인을 하는데, 보통 크롤링을 허용해놓는지 확인하기 위해 대표적인 방탈출 지점들을 찾아봄.

**Comment by kye8524** [comment]
문의드린결과
-업체홈페이지마다 크롤링코드를 따로 만들어야함.
-홈페이지 개발자도구 > 네트워크탭 > 패킷
- 패킷 확인해서 어떤 패킷이 예약현황인지 파악해서 http request를 보내는식으로 정보를 가져옴

각 홈페이지별로 예약현황관련 패킷 확인중.
