### ISSUE TITLE
폴더, 파일 구조

### ISSUE THREAD

**Issue by yossogood8611** [NowEscape/now_escape#3]
- expo DOC 참고 : https://docs.expo.dev/tutorial/build-a-screen/ 
- asset, css, component, page 폴더 구조 찾아서 링크와 함께 댓글 : @thisisdana49 
- 수정된 기능명세서 확인 후 component, page Issue 생성, 스프린트 별 분담 : @yossogood8611 , @thisisdana49

**Comment by thisisdana49** [comment]
1) assets
앱이 동작되고 서비스되는 데에 기본적으로 가지고 있는 이미지 및 아이콘 파일들을 담는 폴더

2) node_modules
리액트 네이티브 & Expo로 앱을 만들면서 설치하게 되는 많은 라이브러리들이 저장되는 장소

3) App.js
리액트 네이티브 앱이 시작되는 출발선 및 진입점
필요한 이미지, 폰트들 준비 하는 장소
준비가 끝나면, 본 화면을 보여준다

4) app.json
앱의 이름, 앱의 출시 버전, 앱이 휴대폰에 설치될때 보여질 아이콘, 앱이 켜질떄 보여지는 스플래시 스크린 화면, 광고설정 등
앱이 가지는 기본 정보들을 설정하는 파일

참고 링크 : https://velog.io/@goohyun1990/Expo-%EC%8B%A4%ED%96%89%ED%95%98%EA%B8%B0
