### ISSUE TITLE
component/label setting 연결 및 코드 수정

### ISSUE THREAD

**Issue by yossogood8611** [NowEscape/now_escape#35]
https://github.com/NowEscape/now_escape/blob/0b00b9a3d70a821a03c002e139d3d22ec248223e/now_escape/components/Label/label.js#L10

```diff
-  {props.type == 'mainLabel' && 
+  {type === 'mainLabel' && 
```

- {type} = props 했으면 props.type 이 아니라 type 으로 써야 함
- === 으로 수정

+ To do : page type이 아닌, label type(종류) 에 따라 onPress에 setting을 맞게 연결 (props에 type 추가 후 onPress 시에 type에 맞는 setting 띄움), 동시에 라벨 오른편의 삼각형은 setting이 떴을 때와 안 떴을 때 위 아래가 바뀌어야 하는데, 그것도 추가해야 함

**Comment by thisisdana49** [comment]
이 부분 코멘트 남겨주신대로 수정하면서 궁금한 점이 생겼습니다!
page type이 아닌 label type에 따라 setting을 연결하면 된다고 하셨는데
onPress시 상위로 값을 넘겨주고 거기서 true일 때에 setting이 뜨게 하는 방식도 괜찮을까요?
아니면 setting을 label이 바로 호출하는게 맞을까요..?

**Comment by yossogood8611** [comment]
두개의 차이점이 뭔지 설명만으로는 잘 모르겠는데 onPress로 type number와 active true/false 를 넘겨줘서 type에 맞는 setting을 on/off 하는걸로 생각했습니다. label component에서 setting을 import 해서 호출하는 식으로 하면 괜찮을 것 같네요!

**Comment by yossogood8611** [comment]
그리고 label props 에 icon 은 사용이 되는건가요? searchPage 보면 date, time은 왼쪽에 아이콘이 있는데, 그것도 수정을 해주셔야 할 것 같아요!

**Comment by yossogood8611** [comment]
page, type마다 오른쪽 이미지가 표시가 되기도하고 안되기도 하는데 이 부분 모두 알맞게 적용할 수 있게 해야 할 것 같습니다!
